### ISSUE TITLE
Workshop Unavailability

### ISSUE THREAD

**Issue by diveyez** [Metis-Team/mts_enhanced#26]
> `[Discord: Diveyez#1878]`

Unable to find on Workshop as a Release.

Is there anyway to get a direct link, or information about this?

**I am willing to help with Development of your creations. 
PLEASE CONTACT ME DIRECTLY!**

**Comment by PhILoXs** [comment]
Hello diveyez, we haven't currently released a workshop version, because some things have to be fixed before that and the problem with this mod is that it is intended to be modular. So that any of the addons in this mod, can be removed without harming the other addons. That can't be depicted in Steam workshop, but with other programs such as A3S or Swifty. We will let you know if we have decided to release it on steam workshop.
